backend:
  name: git-gateway
  branch: main

# 确保这里的路径是正确的
media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "博客文章"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题 (Title)", name: "title", widget: "string" }
      - { label: "描述 (Description)", name: "description", widget: "string" }
      - { label: "发布时间 (PubDatetime)", name: "pubDatetime", widget: "datetime" }
      - { label: "是否精选 (Featured)", name: "featured", widget: "boolean", default: false }
      - { label: "是否草稿 (Draft)", name: "draft", widget: "boolean", default: false }
      - { label: "标签 (Tags)", name: "tags", widget: "list" }
      - { label: "封面图片 (OG Image)", name: "ogImage", widget: "image", optional: true }
      - { label: "正文 (Body)", name: "body", widget: "markdown" }
